=== micahmo/SoundBoard/SoundBoard/AppUpdate.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="AppUpdate">
    <xs:complexType>
        <xs:all>
            <xs:element name="Version" type="xs:string"/>
            <xs:element name="DownloadLink" type="xs:string" minOccurs="0"/>
            <xs:element name="DownloadFileName" type="xs:string" minOccurs="0"/>
            <xs:element name="Downloads" type="ArrayOfDownloadEntry" minOccurs="0"/>
            <xs:element name="VersionNotes" type="xs:string" minOccurs="0"/>
            <xs:element name="ReleaseNotes" type="ArrayOfReleaseNote" minOccurs="0"/>
            <xs:element name="ReleaseDate" type="xs:date"/>
        </xs:all>
    </xs:complexType>
</xs:element>

<xs:complexType name="ArrayOfDownloadEntry">
    <xs:sequence>
        <xs:element name="Download" type="DownloadEntry" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="DownloadEntry">
    <xs:sequence>
        <xs:element name="Link" type="xs:string"/>
        <xs:element name="FileName" type="xs:string" minOccurs="0"/>
        <xs:element name="FileHash" type="FileHash" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="key" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="FileHash">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="algorithm" type="xs:string"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="ArrayOfReleaseNote">
    <xs:sequence>
        <xs:element name="ReleaseNote" type="ReleaseNote" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="ReleaseNote">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:language" use="required"/>
      </xs:extension>
    </xs:simpleContent>
</xs:complexType>

</xs:schema>

=== micahmo/SoundBoard/SoundBoard/VersionInfo.xml
<?xml version="1.0" encoding="utf-8" ?>
<AppUpdate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/micahmo/SoundBoard/master/SoundBoard/AppUpdate.xsd">
  <Version>1.10.0.2</Version>
  <ReleaseDate>2023-03-10</ReleaseDate>
  <!-- Default download -->
  <DownloadLink>https://github.com/micahmo/SoundBoard/releases/download/v1.10.0/SoundBoard.exe</DownloadLink>
  <DownloadFileName>SoundBoard.exe</DownloadFileName>
  <!-- All download options -->
  <Downloads>
    <Download key="portable">
      <Link>https://github.com/micahmo/SoundBoard/releases/download/v1.10.0/SoundBoard.exe</Link>
      <FileName>SoundBoard.exe</FileName>
      <FileHash></FileHash>
    </Download>
  </Downloads>
  <!-- Release notes -->
  <VersionNotes> - Audio recording device can be passed through to an audio playback device (#18)
 - Hotkeys can be assigned to sounds
 - Multiple sounds or a whole folder can be added at once
 - Select sounds with Control- or Shift-Click to update or play multiple at once
 - Sounds can be configured to stop all other sounds when played
 - Sound names are more readable at different sizes (#17)
 - Tabs with currently playing sounds will now be clearly indicated
 - Sounds can trigger other sounds, allowing chaining
 - The default grid layout for new pages can be configured
 - General bug fixes and improvements</VersionNotes>
  <ReleaseNotes></ReleaseNotes>
</AppUpdate>
